export const CONSTANTS = {
    'EMAIL': 'Email',
    'EMAIL_REQRD': 'Email is required',
    'VALID_EMAIL': 'Email must be a valid email address',
    'PSWD_REQRD': 'Password is Required',
    'PSWRD_VALID': 'Password must be at least 6 characters',
    'USERTYPE':[ {id:"" ,value:' -- Select Type -- '},
    {id:'signup',value:'Sign Up'},
    {id:'forgotPassword',value:'Forgot Password'}],
    'CATEGORY':{
        'TITLE': 'Category Name',
        'TITLEERROR': 'Name requried',
        'TITLES':'Enter Category Name',
        'DESCS':'Enter Description',
        'DESCERROR': 'Description requried',
        'DES':'Description',
        'IMAGE':'Upload Image',
        'UPDATEIMAGE':'Update Image',
        'ERRIMAGE':'Image required',
        'TYPE':'Type',
        'TYPEERROR':'Type is required'
     },
     'PRODUCT':{
        'NAME': 'Product Name',
        'PLACENAME': 'Enter name',
        'IMAGE':'Upload Image',
        'UPDATEIMAGE':'Update Image',
        'ERRIMAGE':'Image required',
        'ERRORNAME':'Product Name requried',
        'CATEGORY':'Category',
        'SELECTCAT': 'Select Category',
        'CATERROR':'Category requried',
        'DESCS':'Enter Description',
        'DESCERROR': 'Description requried',
        'DES':'Description',
        'PLACESIZE':'Enter Size',
        'SIZEERROR': 'Size requried',
        'SIZE':'Product Size',
        'PLACECOLOR':'Enter Color',
        'COLORERROR': 'Color requried',
        'COLOR':'Product Color',
        'PLACEQUA':'Enter Quantity',
        'QUAERROR': 'Quantity requried',
        'QUANTITY':'Product Quantity',
        'PLACEPRICE':'Enter Price',
        'PRIERROR': 'Price requried',
        'PRICE':'Product Price',
        'LOC':'Location',
        'LOCPL':'Enter Location',
        'LOCERR':'Location requried'
     },
     'NOTIFICATION':{
      'TITLE': 'Notification title',
      'TITLEERROR': 'Notification title requried',
      'TITLES':'Enter Notification title',
      'DESCS':'Enter Content',
      'DESCERROR': 'Content requried',
      'DES':'Content',
      'STATUS':'Status',
      'STATUSER':'Status requried',
      'TYPE':'User Type',
      'TYPEERR':'User Type requried',
      'USERTYPE':[ {id:"" ,value:' -- Select Type -- '},
      {id:1,value:'General'},
      {id:2,value:'Important'}]
   },
   'BANNER':{
      'NAME': 'Banner Name',
      'PLACENAME': 'Enter banner name',
      'NAMEERR': 'Banner name requried',
      'DESCS':'Enter Description',
      'DESCERROR': 'Description requried',
      'DES':'Description',
      'IMAGEERR':'Image requried',
      'IMAGE':'Banner Image'
   }
     
}